<?php

declare(strict_types=1);

namespace Simtabi\Laranail\Emojis\Core\Enums;

/**
 * Every Emoji version the dataset contains. Used to cap output at what a platform can display.
 *
 * GENERATED by .dev/tools/generate-enums.php from database/generated/emojis.php — do not edit.
 */
enum EmojiVersion: string
{
    case V0_6 = '0.6';
    case V0_7 = '0.7';
    case V1_0 = '1.0';
    case V2_0 = '2.0';
    case V3_0 = '3.0';
    case V4_0 = '4.0';
    case V5_0 = '5.0';
    case V11_0 = '11.0';
    case V12_0 = '12.0';
    case V12_1 = '12.1';
    case V13_0 = '13.0';
    case V13_1 = '13.1';
    case V14_0 = '14.0';
    case V15_0 = '15.0';
    case V15_1 = '15.1';
    case V16_0 = '16.0';
    case V17_0 = '17.0';
    case V18_0 = '18.0';

    public static function latest(): self
    {
        return self::V18_0;
    }

    public function isAtMost(self $other): bool
    {
        return version_compare($this->value, $other->value, '<=');
    }

    public function isNewerThan(self $other): bool
    {
        return version_compare($this->value, $other->value, '>');
    }
}
