<?php

declare(strict_types=1);

namespace Simtabi\Laranail\Emojis\Core\Enums;

use ValueError;

/**
 * The ten Unicode emoji groups, in CLDR order.
 *
 * GENERATED by tools/generate-enums.php from database/generated/emojis.php — do not edit.
 */
enum Group: string
{
    case SmileysAndEmotion = 'smileys_and_emotion';
    case PeopleAndBody = 'people_and_body';
    case Component = 'component';
    case AnimalsAndNature = 'animals_and_nature';
    case FoodAndDrink = 'food_and_drink';
    case TravelAndPlaces = 'travel_and_places';
    case Activities = 'activities';
    case Objects = 'objects';
    case Symbols = 'symbols';
    case Flags = 'flags';

    public static function fromIndex(int $index): self
    {
        return match ($index) {
            0       => self::SmileysAndEmotion,
            1       => self::PeopleAndBody,
            2       => self::Component,
            3       => self::AnimalsAndNature,
            4       => self::FoodAndDrink,
            5       => self::TravelAndPlaces,
            6       => self::Activities,
            7       => self::Objects,
            8       => self::Symbols,
            9       => self::Flags,
            default => throw new ValueError("No emoji group at index {$index}."),
        };
    }

    public function label(): string
    {
        return match ($this) {
            self::SmileysAndEmotion => 'Smileys & Emotion',
            self::PeopleAndBody     => 'People & Body',
            self::Component         => 'Component',
            self::AnimalsAndNature  => 'Animals & Nature',
            self::FoodAndDrink      => 'Food & Drink',
            self::TravelAndPlaces   => 'Travel & Places',
            self::Activities        => 'Activities',
            self::Objects           => 'Objects',
            self::Symbols           => 'Symbols',
            self::Flags             => 'Flags',
        };
    }
}
