<?php

declare(strict_types=1);

// Records the SHA-256 of every downloaded image of a set, so `laranail::emojis.images install` can refuse any
// file that differs from the one this dataset was built and measured from.
//
//   php tools/measure/hash-images.php <set> <cache-dir> <version>
//
// Reads <cache-dir>/<HEXCODE>.svg (the same downloads measure-bounds.mjs reads; see its header) and writes
// database/sources/measured/hashes/<set>.json. Hashes are the first 128 bits, hex: collision and preimage
// resistance of 2^64 and 2^128 respectively, at half the size of the full digest.

[, $set, $cache, $version] = $argv + [null, null, null, null];

if (! is_string($set) || ! is_string($cache) || ! is_string($version) || ! is_dir($cache)) {
    fwrite(STDERR, "usage: php tools/measure/hash-images.php <set> <cache-dir> <version>\n");
    exit(1);
}

$entries = [];

foreach (glob(rtrim($cache, '/') . '/*.svg') ?: [] as $file) {
    $entries[basename($file, '.svg')] = substr(hash_file('sha256', $file), 0, 32);
}

ksort($entries, SORT_STRING);

if (count($entries) < 2500) {
    fwrite(STDERR, "{$set}: only " . count($entries) . " files in {$cache}; download the set first\n");
    exit(1);
}

$out = dirname(__DIR__, 2) . "/database/sources/measured/hashes/{$set}.json";
@mkdir(dirname($out), 0o755, true);
file_put_contents($out, json_encode([
    'about'   => 'SHA-256 (first 128 bits, hex) of each upstream image file. Generated by tools/measure/hash-images.php — do not edit.',
    'set'     => $set,
    'version' => $version,
    'count'   => count($entries),
    'entries' => $entries,
], JSON_UNESCAPED_SLASHES) . "\n");

echo "{$set}: hashed " . count($entries) . " files\n";
