// Measures the drawn bounds of every emoji image in the pinned image sets, so the package can crop the sets'
// built-in padding (Fit::Balanced) or crop to the artwork (Fit::Tight) without ever clipping it.
//
//   cd tools/measure && npm install
//   php tools/measure/image-urls.php <set>
//   (download: see below)
//   node tools/measure/measure-bounds.mjs <set> <urls.tsv> <cache-dir> <version>
//
// <urls.tsv> is "HEXCODE<TAB>URL" per line — build/cache/images/<set>.urls. SVGs are read from
// <cache-dir>/<HEXCODE>.svg; download them first, e.g.
//   awk -F'\t' '{print "build/cache/images/<set>/"$1".svg\t"$2}' build/cache/images/<set>.urls \
//     | xargs -P 6 -L 1 sh -c 'curl -sSf --retry 6 --retry-all-errors -o "$0" "$1"'
// (jsDelivr answers 502 to bursts, hence the low concurrency).
//
// Each SVG is rasterised at 512 px with resvg and the transparent margin on each side is recorded in permille
// of the canvas, rounded *down* so a crop derived from it can never cut into a pixel of artwork.
//
// resvg can abort the whole process on a malformed SVG (a Rust panic JavaScript cannot catch), so rendering
// runs in child processes in batches; a batch that dies is retried one file per process, and a file that still
// kills its process is listed under "unmeasurable" and simply gets no crop.
//
// Output: database/sources/measured/bounds/<set>.json — committed, and consumed by build-dataset.php, which refuses
// it when <version> differs from the set's version in database/sources/upstream.lock.json.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const SIZE = 512;
const ALPHA = 8; // below this alpha a pixel is anti-aliasing haze, not artwork
const BATCH = 200;
const self = fileURLToPath(import.meta.url);

if (process.argv[2] === '--worker') {
  // Worker: measure the files named on STDIN, one JSON line per file.
  const { Resvg } = await import('@resvg/resvg-js');

  for (const file of readFileSync(0, 'utf8').split('\n').filter(Boolean)) {
    const image = new Resvg(readFileSync(file, 'utf8'), { fitTo: { mode: 'width', value: SIZE } }).render();
    const { width, height, pixels } = image;
    let left = width, top = height, right = -1, bottom = -1;

    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        if (pixels[(y * width + x) * 4 + 3] > ALPHA) {
          if (x < left) left = x;
          if (x > right) right = x;
          if (y < top) top = y;
          if (y > bottom) bottom = y;
        }
      }
    }

    const permille = (v, of) => Math.floor((1000 * v) / of);
    const margins = right < 0 ? null : [permille(left, width), permille(top, height), permille(width - 1 - right, width), permille(height - 1 - bottom, height)];
    process.stdout.write(JSON.stringify([file, margins]) + '\n');
  }

  process.exit(0);
}

const [set, urls, cache, version] = process.argv.slice(2);

if (!set || !urls || !cache || !version) {
  console.error('usage: node measure-bounds.mjs <set> <urls.tsv> <cache-dir> <version>');
  process.exit(1);
}

const files = new Map();
let missing = 0;

for (const line of readFileSync(urls, 'utf8').split('\n')) {
  const [hex] = line.split('\t');

  if (!hex) {
    continue;
  }

  const file = `${cache}/${hex}.svg`;

  if (existsSync(file)) {
    files.set(file, hex);
  } else {
    missing++;
  }
}

const run = (batch) => spawnSync(process.execPath, [self, '--worker'], { input: batch.join('\n'), maxBuffer: 64 * 1024 * 1024 });
const entries = {};
const unmeasurable = [];
let blank = 0;

const collect = (stdout) => {
  for (const line of stdout.toString().split('\n').filter(Boolean)) {
    const [file, margins] = JSON.parse(line);

    if (margins === null) {
      blank++;
    } else {
      entries[files.get(file)] = margins;
    }
  }
};

const list = [...files.keys()];

for (let i = 0; i < list.length; i += BATCH) {
  const batch = list.slice(i, i + BATCH);
  const result = run(batch);

  if (result.status === 0) {
    collect(result.stdout);
    continue;
  }

  for (const file of batch) {
    const single = run([file]);

    if (single.status === 0) {
      collect(single.stdout);
    } else {
      unmeasurable.push(files.get(file));
    }
  }
}

const count = Object.keys(entries).length;
const sorted = Object.fromEntries(Object.keys(entries).sort().map((k) => [k, entries[k]]));

writeFileSync(
  `${new URL('../../database/sources/measured/bounds/', import.meta.url).pathname}${set}.json`,
  JSON.stringify({ about: 'Transparent margin per emoji image, permille of the canvas: [left, top, right, bottom], rounded down. Generated by tools/measure/measure-bounds.mjs — do not edit.', set, version, size: SIZE, alphaThreshold: ALPHA, count, unmeasurable: unmeasurable.sort(), entries: sorted }) + '\n',
);

console.log(`${set}: measured ${count}, missing ${missing}, blank ${blank}, unmeasurable ${unmeasurable.length}${unmeasurable.length ? ' (' + unmeasurable.join(' ') + ')' : ''}`);

if (count === 0 || missing + unmeasurable.length > count / 10) {
  process.exit(1);
}
