<?php

declare(strict_types=1);

/**
 * Generates src/Core/Enums/{Group,Subgroup,EmojiVersion,EmojiId}.php from resources/data/emojis.php.
 *
 *   php tools/generate-enums.php           write the enums
 *   php tools/generate-enums.php --check   byte-compare; exit 1 on drift
 *
 * The enums are the typed, IDE-completable face of the dataset (the spatie/emoji idea, as backed enums
 * instead of 3,000 static methods). They are generated from the committed dataset rather than from the
 * upstream sources, so this check needs no network and runs everywhere.
 *
 * EmojiId case names are a public API. A rename upstream must not silently rename a case, so names that
 * already exist are read back from the current file and kept; only new emoji get new cases.
 */

require __DIR__ . '/pint-format.php';
require __DIR__ . '/lib/PhpEmitter.php';

$root = dirname(__DIR__);
$check = in_array('--check', array_slice($argv, 1), true);
$data = require $root . '/resources/data/emojis.php';
$enumDir = $root . '/src/Core/Enums';

$pascal = static function (string $slug): string {
    $name = str_replace(' ', '', ucwords((string) preg_replace('/[^A-Za-z0-9]+/', ' ', $slug)));

    return preg_match('/^\d/', $name) === 1 ? 'E' . $name : $name;
};

$header = "<?php\n\ndeclare(strict_types=1);\n\nnamespace Simtabi\\Laranail\\Emojis\\Core\\Enums;\n\n";
$generated = ' * GENERATED by tools/generate-enums.php from resources/data/emojis.php — do not edit.';

// ---- Group --------------------------------------------------------------------------------------
$cases = '';
$labels = '';
$indexes = '';

foreach ($data['groups'] as $index => $group) {
    $case = $pascal($group['slug']);
    $cases .= "    case {$case} = " . PhpEmitter::string($group['slug']) . ";\n";
    $labels .= "            self::{$case} => " . PhpEmitter::string($group['name']) . ",\n";
    $indexes .= "            {$index} => self::{$case},\n";
}

$files['Group.php'] = $header . "/**\n * The ten Unicode emoji groups, in CLDR order.\n *\n{$generated}\n */\nenum Group: string\n{\n{$cases}\n"
    . "    public static function fromIndex(int \$index): self\n    {\n        return match (\$index) {\n{$indexes}            default => throw new \\ValueError(\"No emoji group at index {\$index}.\"),\n        };\n    }\n\n"
    . "    public function label(): string\n    {\n        return match (\$this) {\n{$labels}        };\n    }\n}\n";

// ---- Subgroup -----------------------------------------------------------------------------------
$cases = '';
$labels = '';
$parents = '';
$indexes = '';
$used = [];

foreach ($data['subgroups'] as $index => $subgroup) {
    $case = $pascal($subgroup['slug']);
    isset($used[$case]) && throw new RuntimeException("Duplicate subgroup case {$case}");
    $used[$case] = true;
    $cases .= "    case {$case} = " . PhpEmitter::string($subgroup['slug']) . ";\n";
    $labels .= "            self::{$case} => " . PhpEmitter::string($subgroup['name']) . ",\n";
    $parents .= "            self::{$case} => Group::" . $pascal($data['groups'][$subgroup['group']]['slug']) . ",\n";
    $indexes .= "            {$index} => self::{$case},\n";
}

$files['Subgroup.php'] = $header . "/**\n * The Unicode emoji subgroups, in CLDR order.\n *\n{$generated}\n */\nenum Subgroup: string\n{\n{$cases}\n"
    . "    public static function fromIndex(int \$index): self\n    {\n        return match (\$index) {\n{$indexes}            default => throw new \\ValueError(\"No emoji subgroup at index {\$index}.\"),\n        };\n    }\n\n"
    . "    public function label(): string\n    {\n        return match (\$this) {\n{$labels}        };\n    }\n\n"
    . "    public function group(): Group\n    {\n        return match (\$this) {\n{$parents}        };\n    }\n}\n";

// ---- EmojiVersion -------------------------------------------------------------------------------
$versions = array_values(array_unique(array_map(static fn (array $e): string => $e[6], $data['emojis'])));
usort($versions, 'version_compare');
$cases = '';

foreach ($versions as $version) {
    $cases .= '    case V' . str_replace('.', '_', $version) . " = '{$version}';\n";
}

$latest = 'V' . str_replace('.', '_', end($versions));

$files['EmojiVersion.php'] = $header . "/**\n * Every Emoji version the dataset contains. Used to cap output at what a platform can display.\n *\n{$generated}\n */\nenum EmojiVersion: string\n{\n{$cases}\n"
    . "    public static function latest(): self\n    {\n        return self::{$latest};\n    }\n\n"
    . "    public function isAtMost(self \$other): bool\n    {\n        return version_compare(\$this->value, \$other->value, '<=');\n    }\n\n"
    . "    public function isNewerThan(self \$other): bool\n    {\n        return version_compare(\$this->value, \$other->value, '>');\n    }\n}\n";

// ---- EmojiId ------------------------------------------------------------------------------------
$existing = [];
$current = $enumDir . '/EmojiId.php';

if (is_file($current) && preg_match_all("/case (\\w+) = '([0-9A-F-]+)';/", (string) file_get_contents($current), $m, PREG_SET_ORDER) > 0) {
    foreach ($m as [, $case, $hex]) {
        $existing[$hex] = $case;
    }
}

$cases = '';
$used = [];
$count = 0;

foreach ($data['emojis'] as $hex => $emoji) {
    $hex = (string) $hex;

    if ($emoji[9] !== null) {
        continue; // skin-tone variants are reached through withSkinTone(), not a case each
    }

    $case = $existing[$hex] ?? $pascal($emoji[2]);
    isset($used[$case]) && throw new RuntimeException("Duplicate EmojiId case {$case} for {$hex}");
    $used[$case] = true;
    $cases .= "    case {$case} = '{$hex}';\n";
    $count++;
}

$files['EmojiId.php'] = $header . "/**\n * One case per emoji that is not a skin-tone variant ({$count} cases), valued by hexcode.\n *\n"
    . " *     Emojis::get(EmojiId::GrinningFace)->withSkinTone(SkinTone::Medium);\n *\n"
    . " * Case names are frozen once published: an upstream rename keeps the existing case.\n *\n{$generated}\n */\nenum EmojiId: string\n{\n{$cases}}\n";

$drift = [];

foreach ($files as $name => $source) {
    $source = laranail_pint_format($source);
    $path = $enumDir . '/' . $name;

    if ($check) {
        if (! is_file($path) || file_get_contents($path) !== $source) {
            $drift[] = $name;
        }

        continue;
    }

    file_put_contents($path, $source);
}

if ($check) {
    if ($drift !== []) {
        fwrite(STDERR, 'generate-enums: stale ' . implode(', ', $drift) . " (run php tools/generate-enums.php)\n");

        exit(1);
    }

    fwrite(STDOUT, 'generate-enums --check: ' . count($files) . " enums in sync.\n");

    exit(0);
}

fwrite(STDOUT, 'Wrote ' . count($files) . " enums ({$count} EmojiId cases).\n");
