<?php

declare(strict_types=1);

// The development tools under .dev/ do not ship, but they gate what does: these checks keep them honest.

it('lists every generator once, so regenerate and sync-check cannot drift apart', function (): void {
    $tools = dirname(__DIR__, 2) . '/.dev/tools';
    require_once $tools . '/lib/Generators.php';

    $listed = array_values(Generators::all());
    $present = array_map(basename(...), [
        ...glob($tools . '/build-dataset.php') ?: [],
        ...glob($tools . '/generate-*.php') ?: [],
        ...glob($tools . '/*-doc.php') ?: [],
    ]);

    // A generator missing from the list is regenerated by nobody and checked by nothing.
    expect(count($present))->toBeGreaterThanOrEqual(4)
        ->and($listed)->toEqualCanonicalizing($present)
        ->and($listed[0])->toBe('build-dataset.php');

    foreach (['regenerate.php', 'sync-check.php'] as $runner) {
        expect((string) file_get_contents("{$tools}/{$runner}"))->toContain('Generators::all()');
    }

    expect((string) file_get_contents("{$tools}/refresh.php"))->toContain('regenerate.php');
});
