<?php

declare(strict_types=1);

// The development tools under .dev/ do not ship, but they gate what does: these checks keep them honest.

it('lists every generator once, so regenerate and sync-check cannot drift apart', function (): void {
    $tools = dirname(__DIR__, 2) . '/.dev/tools';
    require_once $tools . '/lib/Generators.php';

    $listed = array_values(Generators::all());
    $present = array_map(basename(...), [
        ...glob($tools . '/build-dataset.php') ?: [],
        ...glob($tools . '/generate-*.php') ?: [],
        ...glob($tools . '/*-doc.php') ?: [],
    ]);

    // A generator missing from the list is regenerated by nobody and checked by nothing.
    expect(count($present))->toBeGreaterThanOrEqual(4)
        ->and($listed)->toEqualCanonicalizing($present)
        ->and($listed[0])->toBe('build-dataset.php');

    foreach (['regenerate.php', 'sync-check.php'] as $runner) {
        expect((string) file_get_contents("{$tools}/{$runner}"))->toContain('Generators::all()');
    }

    expect((string) file_get_contents("{$tools}/refresh.php"))->toContain('regenerate.php');
});

it('sends a GitHub token to the GitHub API only, so a download never leaks it', function (string $url, ?string $token, ?string $expected): void {
    require_once dirname(__DIR__, 2) . '/.dev/tools/lib/GitHubAuth.php';

    expect(GitHubAuth::headerFor($url, $token))->toBe($expected);
})->with([
    'GitHub API, token'      => ['https://api.github.com/repos/googlefonts/noto-emoji/git/trees/abc', 'ghs_x', 'Authorization: Bearer ghs_x'],
    'GitHub API, uppercase'  => ['https://API.GitHub.com/repos/a/b', 'ghs_x', 'Authorization: Bearer ghs_x'],
    'no token'               => ['https://api.github.com/repos/a/b', null, null],
    'empty token'            => ['https://api.github.com/repos/a/b', '', null],
    'a CDN'                  => ['https://cdn.jsdelivr.net/npm/emojibase-data/en/data.json', 'ghs_x', null],
    'raw GitHub content'     => ['https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json', 'ghs_x', null],
    'lookalike host'         => ['https://api.github.com.evil.example/repos', 'ghs_x', null],
    'credentials in the URL' => ['https://user@api.github.com/repos/a/b', 'ghs_x', null],
    'plain http'             => ['http://api.github.com/repos/a/b', 'ghs_x', null],
    'another port'           => ['https://api.github.com:8443/repos/a/b', 'ghs_x', null],
]);

it('downloads every GitHub API source through the token helper', function (): void {
    $lock = json_decode((string) file_get_contents(dirname(__DIR__, 2) . '/database/sources/upstream.lock.json'), true, flags: JSON_THROW_ON_ERROR);
    $sources = $lock['sources'] ?? $lock;
    $api = array_filter($sources, static fn (mixed $s): bool => is_array($s) && str_starts_with((string) ($s['url'] ?? ''), 'https://api.github.com/'));
    $script = (string) file_get_contents(dirname(__DIR__, 2) . '/.dev/tools/build-dataset.php');

    expect(count($api))->toBeGreaterThanOrEqual(1)
        ->and($script)->toContain('GitHubAuth::curlArguments($source[\'url\'])');
});
